# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radistart2.ui'
#
# Created: Mon Mar 24 08:47:01 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtNetwork import *
from PyQt4.QtWebKit import QWebSettings
import config, webbrowser


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1100, 844)
        #Style auswählen
        MainWindow.setStyle(QtGui.QStyleFactory.create("cleanlooks"))
        
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Icons/RS/Radistart.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setStyleSheet(_fromUtf8("background-color:#AFBCE4;\n"
"font: 12pt \"Verdana\";"))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.BWord = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BWord.sizePolicy().hasHeightForWidth())
        self.BWord.setSizePolicy(sizePolicy)
        self.BWord.setStyleSheet(_fromUtf8("background-color:#22238D"))
        self.BWord.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Word.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BWord.setIcon(icon1)
        self.BWord.setIconSize(QtCore.QSize(50, 50))
        self.BWord.setObjectName(_fromUtf8("BWord"))
        self.verticalLayout.addWidget(self.BWord)
        self.BExcel = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BExcel.sizePolicy().hasHeightForWidth())
        self.BExcel.setSizePolicy(sizePolicy)
        self.BExcel.setStyleSheet(_fromUtf8("background-color:#245f10"))
        self.BExcel.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Excel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BExcel.setIcon(icon2)
        self.BExcel.setIconSize(QtCore.QSize(50, 50))
        self.BExcel.setObjectName(_fromUtf8("BExcel"))
        self.verticalLayout.addWidget(self.BExcel)
        self.BEmail = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BEmail.sizePolicy().hasHeightForWidth())
        self.BEmail.setSizePolicy(sizePolicy)
        self.BEmail.setStyleSheet(_fromUtf8("background-color:#edd31a"))
        self.BEmail.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Outlook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BEmail.setIcon(icon3)
        self.BEmail.setIconSize(QtCore.QSize(50, 50))
        self.BEmail.setObjectName(_fromUtf8("BEmail"))
        self.verticalLayout.addWidget(self.BEmail)
        self.BOrbis = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BOrbis.sizePolicy().hasHeightForWidth())
        self.BOrbis.setSizePolicy(sizePolicy)
        self.BOrbis.setStyleSheet(_fromUtf8("background-color:#FFFFFF"))
        self.BOrbis.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Orbis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BOrbis.setIcon(icon4)
        self.BOrbis.setIconSize(QtCore.QSize(50, 50))
        self.BOrbis.setObjectName(_fromUtf8("BOrbis"))
        self.verticalLayout.addWidget(self.BOrbis)
        self.BImpaxEE = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BImpaxEE.sizePolicy().hasHeightForWidth())
        self.BImpaxEE.setSizePolicy(sizePolicy)
        self.BImpaxEE.setStyleSheet(_fromUtf8("background-color:#FFFFFF"))
        self.BImpaxEE.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Impax.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BImpaxEE.setIcon(icon5)
        self.BImpaxEE.setIconSize(QtCore.QSize(50, 50))
        self.BImpaxEE.setObjectName(_fromUtf8("BImpaxEE"))
        self.verticalLayout.addWidget(self.BImpaxEE)
        self.BIntranet = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BIntranet.sizePolicy().hasHeightForWidth())
        self.BIntranet.setSizePolicy(sizePolicy)
        self.BIntranet.setStyleSheet(_fromUtf8("background-color:#22238D"))
        self.BIntranet.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Intranet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BIntranet.setIcon(icon6)
        self.BIntranet.setIconSize(QtCore.QSize(50, 50))
        self.BIntranet.setObjectName(_fromUtf8("BIntranet"))
        self.verticalLayout.addWidget(self.BIntranet)
        self.BIntranetR = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BIntranetR.sizePolicy().hasHeightForWidth())
        self.BIntranetR.setSizePolicy(sizePolicy)
        self.BIntranetR.setStyleSheet(_fromUtf8("background-color:#787d7b"))
        self.BIntranetR.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("IntranetR.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BIntranetR.setIcon(icon7)
        self.BIntranetR.setIconSize(QtCore.QSize(50, 50))
        self.BIntranetR.setObjectName(_fromUtf8("BIntranetR"))
        self.verticalLayout.addWidget(self.BIntranetR)
        self.BRoxtra = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BRoxtra.sizePolicy().hasHeightForWidth())
        self.BRoxtra.setSizePolicy(sizePolicy)
        self.BRoxtra.setStyleSheet(_fromUtf8("background-color:#5FCFF1"))
        self.BRoxtra.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Roxtra.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BRoxtra.setIcon(icon8)
        self.BRoxtra.setIconSize(QtCore.QSize(50, 50))
        self.BRoxtra.setObjectName(_fromUtf8("BRoxtra"))
        self.verticalLayout.addWidget(self.BRoxtra)
        self.BLogbuch = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BLogbuch.sizePolicy().hasHeightForWidth())
        self.BLogbuch.setSizePolicy(sizePolicy)
        self.BLogbuch.setStyleSheet(_fromUtf8("background-color:#F5D60f"))
        self.BLogbuch.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Logbuch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BLogbuch.setIcon(icon9)
        self.BLogbuch.setIconSize(QtCore.QSize(50, 50))
        self.BLogbuch.setObjectName(_fromUtf8("BLogbuch"))
        self.verticalLayout.addWidget(self.BLogbuch)
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color:#FFFFFF"))
        self.pushButton_2.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("TkMed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.BSPX = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSPX.sizePolicy().hasHeightForWidth())
        self.BSPX.setSizePolicy(sizePolicy)
        self.BSPX.setStyleSheet(_fromUtf8("background-color:#3E4572"))
        self.BSPX.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("SPX.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSPX.setIcon(icon11)
        self.BSPX.setIconSize(QtCore.QSize(50, 50))
        self.BSPX.setObjectName(_fromUtf8("BSPX"))
        self.verticalLayout.addWidget(self.BSPX)
        self.BSpeiseplan = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSpeiseplan.sizePolicy().hasHeightForWidth())
        self.BSpeiseplan.setSizePolicy(sizePolicy)
        self.BSpeiseplan.setStyleSheet(_fromUtf8("background-color:#163563"))
        self.BSpeiseplan.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("Speiseplan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BSpeiseplan.setIcon(icon12)
        self.BSpeiseplan.setIconSize(QtCore.QSize(50, 50))
        self.BSpeiseplan.setObjectName(_fromUtf8("BSpeiseplan"))
        self.verticalLayout.addWidget(self.BSpeiseplan)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.webView = QtWebKit.QWebView(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setStyleSheet(_fromUtf8(""))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8(config.IP)))
        self.webView.setObjectName(_fromUtf8("webView"))
        
        self.webView.settings().setAttribute(QWebSettings.PluginsEnabled, True)
        
        self.gridLayout.addWidget(self.webView, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.BTele = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTele.sizePolicy().hasHeightForWidth())
        self.BTele.setSizePolicy(sizePolicy)
        self.BTele.setStyleSheet(_fromUtf8("background-color:#EFC58B"))
        self.BTele.setObjectName(_fromUtf8("BTele"))
        self.horizontalLayout.addWidget(self.BTele)
        self.BRVPa = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BRVPa.sizePolicy().hasHeightForWidth())
        self.BRVPa.setSizePolicy(sizePolicy)
        self.BRVPa.setStyleSheet(_fromUtf8("background-color:#EFC58B"))
        self.BRVPa.setObjectName(_fromUtf8("BRVPa"))
        self.horizontalLayout.addWidget(self.BRVPa)
        self.BRVP = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BRVP.sizePolicy().hasHeightForWidth())
        self.BRVP.setSizePolicy(sizePolicy)
        self.BRVP.setStyleSheet(_fromUtf8("background-color:#EFC58B"))
        self.BRVP.setObjectName(_fromUtf8("BRVP"))
        self.horizontalLayout.addWidget(self.BRVP)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.BS1l3nz = QtGui.QPushButton(self.centralWidget)
        self.BS1l3nz.setStyleSheet(_fromUtf8(""))
        self.BS1l3nz.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("s1l3nzcodes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BS1l3nz.setIcon(icon13)
        self.BS1l3nz.setIconSize(QtCore.QSize(50, 50))
        self.BS1l3nz.setObjectName(_fromUtf8("BS1l3nz"))
        self.verticalLayout_2.addWidget(self.BS1l3nz)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        def Tele():
            self.webView.setUrl(QtCore.QUrl(_fromUtf8(config.IP)))

        def RVPn():
            self.webView.setUrl(QtCore.QUrl(_fromUtf8(config.aRVPn)))

        def RVPa():
            self.webView.setUrl(QtCore.QUrl(_fromUtf8(config.aRVPa)))

        def SPX():
            self.webView.setUrl(QtCore.QUrl(_fromUtf8(config.aSPXa)))
            
        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.BTele, QtCore.SIGNAL(_fromUtf8("clicked()")), Tele)
        QtCore.QObject.connect(self.BRVP, QtCore.SIGNAL(_fromUtf8("clicked()")), RVPn)
        QtCore.QObject.connect(self.BRVPa, QtCore.SIGNAL(_fromUtf8("clicked()")), RVPa)
        QtCore.QObject.connect(self.BWord, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FWord)
        QtCore.QObject.connect(self.BExcel, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FExcel)
        QtCore.QObject.connect(self.BEmail, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FEmail)
        QtCore.QObject.connect(self.BOrbis, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FOrbis)
        QtCore.QObject.connect(self.BImpaxEE, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FImpax)
        QtCore.QObject.connect(self.BIntranet, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FIntranet)
        QtCore.QObject.connect(self.BIntranetR, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FIntranetR)
        QtCore.QObject.connect(self.BRoxtra, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FRoxtra)
        QtCore.QObject.connect(self.BLogbuch, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FLogbuch)
        QtCore.QObject.connect(self.BSPX, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FSpeiseplan)
        QtCore.QObject.connect(self.BSpeiseplan, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FSpeiseplan)
        QtCore.QObject.connect(self.BS1l3nz, QtCore.SIGNAL(_fromUtf8("clicked()")), config.FWord)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Radistart 2", None))
        self.BTele.setText(_translate("MainWindow", "Telefonbuch", None))
        self.BRVPa.setText(_translate("MainWindow", "RVP aktuell (beta)", None))
        self.BRVP.setText(_translate("MainWindow", "RVP nächste Woche (beta)", None))
        self.label_3.setText(_translate("MainWindow", config.User, None))
        self.label_2.setText(_translate("MainWindow", config.Host, None))
        self.label.setText(_translate("MainWindow", config.Date2, None))
        self.label_4.setText(_translate("MainWindow", "", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

